name: Build

on:
  push:
    branches:
      - '**' # only run on branches
  release:
    types: [published]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Checkout SDL2
      uses: actions/checkout@v3
      with:
        repository: libsdl-org/SDL
        ref: release-2.28.x
        path: SDL2

    - name: Install deps
      run: |
        sudo apt update && sudo apt install gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf

    - name: Configure SDL
      run: cmake -S SDL2 -B sdl2-build -DCMAKE_TOOLCHAIN_FILE=./arm.toolchain -DSDL_LIBSAMPLERATE=0 -DCMAKE_INSTALL_PREFIX=./sysroot

    - name: Build SDL
      run: cmake --build sdl2-build --config $BUILD_TYPE -j 2
